
---
- name: Set OS defaults
  connection: local
  hosts: localhost
  tasks:

    - name: Ensure screenshots dir
      ansible.builtin.file:
        path: "{{ screenshotsDirectory }}"
        state: directory
        mode: '0755'

    - name: Set screenshot dir
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "{{ screenshotsDirectory }}"
      notify: Restart SystemUIServer

    - name: Set screenshot format
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: type
        type: string
        value: PNG
      notify: Restart SystemUIServer

    - name: Show hidden files
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true
      notify: Restart Finder

    - name: Show path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppShowPathbar
        type: bool
        value: true
      notify: Restart Finder

    - name: Disable DS_Store files
      community.general.osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true
      notify: Restart Finder

  handlers:
    - name: Restart Finder
      command: killall Finder

    - name: Restart SystemUIServer
      command: killall SystemUIServer
