
---
- name: Set OS defaults
  connection: local
  hosts: localhost
  vars:
    screenshotsDirectory: "{{ ansible_facts.env.HOME }}/Documents/Screenshots"
  tasks:

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "{{ screenshotsDirectory }}"
        state: directory
        mode: '0755'

    - name: Set screenshot dir
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "{{ screenshotsDirectory }}"
      notify: Restart SystemUIServer

    - name: Show hidden files
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true
      notify: Restart Finder

    - name: Show path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: AppShowPathbar
        type: bool
        value: true
      notify: Restart Finder

    # - name: Disable DS_Store files
    #   community.general.osx_defaults:
    #     domain: com.apple.desktopservices
    #     key: DSDontWriteNetworkStores
    #     type: bool
    #     value: true
    #   notify: Restart finder

  handlers:
    - name: Restart Finder
      command: killall Finder

    - name: Restart SystemUIFinder
      command: killall SystemUIFinder
