
screenshotsDirectory: "{{ ansible_facts.env.HOME }}/Documents/Screenshots"
omzPath: "{{ ansible_facts.env.HOME }}/.oh-my-zsh"
dotfilesRepo: "git@github.com:TBeijen/dotfiles.git"
sshConfigRepo: "git@codeberg.org:TBeijen/ssh_config.git"
workspacesRepo: "git@codeberg.org:TBeijen/workspaces.git"

# Brew settings
install_homebrew_if_missing: true
upgrade_homebrew_packages: false
update_homebrew: false

brew_cask_packages:
  - name: citrix-workspace
  - name: docker
  - name: evernote
  - name: gimp
  - name: iterm2
  - name: notion
  - name: signal
  - name: slack
  - name: spotify
  - name: sublime-text
    # Hangs on start, installed tailscale from app store which works :/
  - name: tailscale
    state: absent
  - name: tunnelblick
  - name: visual-studio-code
  - name: whatsapp
  - name: wkhtmltopdf
  # - name: app-wanting-to-uninstall
  #   state: absent

brew_packages:
  - name: autoenv
  - name: awscli
  - name: Azure/kubelogin/kubelogin
  - name: azure-cli
  - name: gnupg
  - name: gpg2
  - name: helm
  - name: jq
  - name: k6
  - name: kubectl
  - name: minikube
  - name: nvm
  - name: pinentry-mac
  - name: pyenv
  - name: pyenv-virtualenv
  - name: qemu
  - name: socket_vmnet
  - name: stern
  - name: tfenv
  - name: wget
  - name: yh
  - name: yq

brew_taps: []
#  - name: homebrew/cask-fonts
#    state: present
#  - name: hashicorp/tap
#    state: present
