
screenshotsDirectory: "{{ ansible_facts.env.HOME }}/Documents/Screenshots"
omzPath: "{{ ansible_facts.env.HOME }}/.oh-my-zsh"
dotfilesRepo: "git@github.com:TBeijen/dotfiles.git"
sshConfigRepo: "git@codeberg.org:TBeijen/ssh_config.git"
workspacesRepo: "git@codeberg.org:TBeijen/workspaces.git"

# Brew settings
install_homebrew_if_missing: true
upgrade_homebrew_packages: false
update_homebrew: false

brew_cask_packages:
  - name: citrix-workspace
  - name: db-browser-for-sqlite
  - name: docker
  - name: drawio
  - name: evernote
  - name: firefox
  - name: gimp
  - name: iterm2
  - name: languagetool
  - name: microsoft-teams
  - name: notion
  - name: pgadmin4
  - name: signal
  - name: slack
  - name: sourcetree
  - name: spotify
  - name: sublime-text
    # Hangs on start, installed tailscale from app store which works :/
  - name: tailscale
    state: absent
  - name: teamviewer
  - name: temurin
  - name: tunnelblick
  - name: visual-studio-code
  - name: whatsapp
  - name: windows-app
  - name: wireshark
  - name: wkhtmltopdf
  - name: yed
  # - name: app-wanting-to-uninstall
  #   state: absent

brew_packages:
  - name: argocd
  - name: argoproj/tap/kubectl-argo-rollouts
  - name: autoenv
  - name: awscli
  - name: azcopy
  - name: Azure/kubelogin/kubelogin
  - name: azure-cli
  - name: cloudflare/cloudflare/cloudflared
  - name: colima
  - name: docker-compose
  - name: curl
  - name: crane
  - name: direnv
  - name: dnsmasq
  - name: font-meslo-lg-nerd-font
  - name: gh
  - name: gnupg
  - name: go
  - name: go-task
  - name: gpg2
  - name: harlequin
  - name: hashicorp/tap/packer
  - name: hcloud
  - name: helm
  - name: jandedobbeleer/oh-my-posh/oh-my-posh
  - name: jq
  - name: k3d
  - name: k6
  - name: k9s
  - name: kubectl
  - name: minikube
  - name: nvm
  - name: opa
  - name: openfga/tap/fga
  - name: opentofu
  - name: pandoc
  - name: pinentry-mac
  - name: pyenv
  - name: pyenv-virtualenv
  - name: qemu
  - name: siderolabs/tap/talosctl
  - name: skopeo
  - name: socket_vmnet
  - name: stern
  - name: sqlite
  - name: talosctl
  - name: testssl
  - name: tfenv
  - name: tree
  - name: trivy
  - name: watch
  - name: wget
  - name: yamllint
    state: absent
  - name: yh
  - name: yq

brew_taps: []
#  - name: homebrew/cask-fonts
#    state: present
#  - name: hashicorp/tap
#    state: present
